### ISSUE TITLE
error number 13?

### ISSUE THREAD

**Issue by ozzy80085** [rajkumardusad/Tool-X#133]
i have had this problem no matter what i do
and happen when i use wifi_deauth also someone help

[✔] Fake Access point started on wlan0mon, SSID fuck_u MAC 33:ba:07:ac:0f:ce
[𝓲] Press Ctrl+C for stop...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.4', 'console_scripts', 'websploit')()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/websploit.py", line 74, in start_wsf
    Main().cmdloop()
  File "/data/data/com.termux/files/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/data/data/com.termux/files/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/websploit.py", line 35, in do_use
    module.cmdloop()
  File "/data/data/com.termux/files/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/data/data/com.termux/files/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/websploit-4.0.4-py3.8.egg/websploit/modules/wifi_fap.py", line 35, in do_execute
    sendp(frame, inter=0.1, iface=self.parameters['iface'], loop=1)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy/sendrecv.py", line 335, in sendp
    socket = socket or conf.L2socket(iface=iface, *args, **kargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/scapy/arch/linux.py", line 467, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/data/data/com.termux/files/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied

**Comment by rajkumardusad** [comment]
Hey @ozzy80085 may tere is a permission error, try with root access like sudo or somthing else?
